# Homework #2: Simple Neural Network Implementation using Numpy

Today we will build a simple neural network from scratch in Python using only the numpy library. We will follow the instructions from the following lin https://iamtrask.github.io/2015/07/12/basic-python-network/k:
Basic Python Network
(Note: The code in the website is written in Python 2, and not Pytho, try writing the code yourself before reverting to the online examplen 
#1: Import Librarit numpy as np


In [ ]:
import numpy as np

### Define the Sigmoid Function and its Derivative
- Construct a function returning a sigmoid function:
$ \sigma(x) = \frac{1}{1 + e^{-x}} $
- Construct a function returning the derivative of a sigmoid function:
$ \frac{d\sigma(x)}{dx} = \sigma(x)(1 - \sigma(x)) $

### Initialize Weights
Build an array of three weights (3x1 array – think why these dimensions!) and initialize their value randomly. (It is good practice to use weights with normal distribution of $ \mu = 0 $ and  $ \sigma = \frac{1}{3}  $ )

In [189]:
def sigmo(x):
    return 1 / (1 + np.exp(-x))
def sigmo_der(x):
    return sigmo(x)*(1-sigmo(x))

### Training the Neural Network
Create a loop, iterating 1000 times (equal to the desired number of learning steps). For each iteration, calculate the difference between the network prediction and the real value of y. Multiply that difference with the sigmoid derivative and use the dot product of this number with the input layer to update your weights for the next iteration.
- Input and Output Data Sets
``` python
X = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1]])

y = np.array([[0],
              [0],
              [1],
              [1]])on. 	


In [ ]:
learning_rat = 0.1
bias = np.array([[0.2],[0.2],[0.2],[0.2]]) 
weights = np.zeros((3,1))
for i in range(3):
    weights[i][0] = np.random.normal(0,0.333) #mean=0, std = 1/3
print(weights)
#-------------------
X = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1]])

y_real = np.array([[0],
              [0],
              [1],
              [1]]) 


[[ 0.52643]
 [-0.46718]
 [ 0.23705]]


In [198]:
#print(weights)
#np.dot(X[1],weights)
#y_real = y_real.astype(float)
    #y_predict = y_predict.astype(float)

#print("our y predict is:",y_predict[q])
    #print(y_predict)
    #print(y_predict[0].astype(float))
    
print(type(y_real[1]))
print(len(X))

y2 = np.array([[2],[4],[10],[0]])
print(y_real - y2)

<class 'numpy.ndarray'>
4
[[-2]
 [-4]
 [-9]
 [ 1]]


# ------------------------------

In [199]:
#BackPropagation:
#y_predict = np.array([[0],[0],[0],[0]])
bias = np.array([[0.2],[0.2],[0.2],[0.2]]) 
for i in range(3):
    weights[i][0] = np.random.normal(0,0.333) #mean=0, std = 1/3

#-------------------

y_predict = np.zeros((4,1))
for i in range(1000):

    #forward culculation:
    for q in range(len(X)):
        y_predict[q] = sigmo(np.dot(X[q],weights) + bias[q])
  

    #diffrence culc...(aka error)
    Ero = 0
    for w in range(len(y_predict)):
        Ero += (y_predict[w] - y_real[w]) 
    print("Numero:",i,"--->",Ero)

    #changing weights culc:
    for w in range(len(y_predict)):
        for i in range(len(weights)):

            diff = (y_predict[w] - y_real[w]) * y_predict[w] *(1 - y_predict[w]) * X[w][i]
            #print("diff is:",diff)
            weights[i] = weights[i] - learning_rat*diff
        
            bias_diff = (y_predict[w] - y_real[w]) * y_predict[w] *(1 - y_predict[w]) 
            bias[i] = bias[i] - learning_rat*bias_diff

    print("Now we:\n",weights,"Erorr->",Ero)



Numero: 0 ---> [0.16746]
Now we:
 [[-0.39402]
 [ 0.21293]
 [ 0.06903]] Erorr-> [0.16746]
Numero: 1 ---> [0.17354]
Now we:
 [[-0.36885]
 [ 0.21027]
 [ 0.06571]] Erorr-> [0.17354]
Numero: 2 ---> [0.17912]
Now we:
 [[-0.34391]
 [ 0.2075 ]
 [ 0.06221]] Erorr-> [0.17912]
Numero: 3 ---> [0.18421]
Now we:
 [[-0.3192 ]
 [ 0.20463]
 [ 0.05854]] Erorr-> [0.18421]
Numero: 4 ---> [0.18883]
Now we:
 [[-0.29471]
 [ 0.20165]
 [ 0.05469]] Erorr-> [0.18883]
Numero: 5 ---> [0.19298]
Now we:
 [[-0.27044]
 [ 0.19858]
 [ 0.05069]] Erorr-> [0.19298]
Numero: 6 ---> [0.19669]
Now we:
 [[-0.2464 ]
 [ 0.19541]
 [ 0.04653]] Erorr-> [0.19669]
Numero: 7 ---> [0.19996]
Now we:
 [[-0.22256]
 [ 0.19216]
 [ 0.04222]] Erorr-> [0.19996]
Numero: 8 ---> [0.20282]
Now we:
 [[-0.19894]
 [ 0.18882]
 [ 0.03778]] Erorr-> [0.20282]
Numero: 9 ---> [0.20527]
Now we:
 [[-0.17553]
 [ 0.1854 ]
 [ 0.0332 ]] Erorr-> [0.20527]
Numero: 10 ---> [0.20735]
Now we:
 [[-0.15232]
 [ 0.1819 ]
 [ 0.02851]] Erorr-> [0.20735]
Numero: 11 ---> [0.2

# ${\color{pink}\mathbb{MATH}}$

### First, we are going to use this:
$$

{O_j}^{l} = \sigma( \sum w_{ij}^{l}O_{i}^{l-1} ) = \sigma(z_j^l) \\-\\ z_j^l = \sum w_{ij}^{l}{O}^{l-1} 
\\-\\{O_j}^{l} = \sigma(z) \\-\\ L = \frac{1}{2} \sum_n (O_{n}^{l}-y_n)^2
$$


$$
\frac{dE}{dw_{ij}^{l}} = \frac{dE}{dO_{j}^{l}} \frac{dO_{j}^{l}}{dw_{ij}^{l}} \\ \frac{dO_{j}^{l}}{dw_{ij}^{l}} = \frac{dO_{j}^{l}}{dz_j^l} \frac{dz_j^l}{dw_{ij}^{l}}
\\-\\ \frac{dE}{dw_{ij}^{l}} = \frac{dE}{dO_{j}^{l}} \frac{dO_{j}^{l}}{dz_j^l} \frac{dz_j^l}{dw_{ij}^{l}}

$$

simple derievation:
$$
\frac{dO_{j}^{l}}{dz_j^l} = \sigma'(z_j^l) = \sigma(z_j^l) (1- \sigma(z_j^l)) = O_{j}^{l} (1-O_{j}^{l}) \\-\\
\frac{dz_j^l}{dw_{ij}^{l}} = O_{j}^{l-1} \\-\\
\frac{dE}{dO_{j}^{l}} = O_{k}^{l} - Y_k = \delta_k
$$

### Finally:
$$
\frac{dE}{dw_{ij}^{l}} = (O_{k}^{l} - Y_k) \cdot  O_{j}^{l-1} \cdot  O_{j}^{l} (1-O_{j}^{l}) 
\\-----------\\----\\
\frac{dE}{dw_{ij}^{l}} = \delta_k \cdot  O_{j}^{l-1} \cdot  O_{j}^{l} (1-O_{j}^{l})

$$

and for the bias its just the same.
$$
\frac{dE}{db_j^l} = \frac{dE}{dO_{j}^{l}} \frac{dO_{j}^{l}}{dz_j^l} \frac{dz_j^l}{db_j^l} \\ \frac{dz_j^l}{db_j^l} = 1
\\-\\ \frac{dE}{db_j^l} = \delta_k  \cdot  O_{j}^{l} (1-O_{j}^{l})


$$